import { StyleSheet, Dimensions } from 'react-native';
export default StyleSheet.create({
    container: {
        flexDirection: "row",
        alignItems: "center",
        flexWrap: "nowrap",
        width: '100%',
        height: 14,
        marginTop: 40,
        marginLeft: 17
    },
    group11: {
        width: '14%',
        height: 14,
        textAlign: "center"
    },
    rect8: {
        width: 14,
        height: 14,
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun3: {
        color: "#3329FF",
        fontSize: 12,
        marginTop: 5,
    },
    group12: {
        width: '14%',
        height: 14,
    },
    rect9: {
        width: 14,
        height: 14,
        backgroundColor: "#E6E6E6",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun4: {
        color: "#3329FF",
        fontSize: 12,
        margin: 0,
        marginTop: 5,
        marginLeft: -2
    },
    group13: {
        width: '14%',
        height: 14,
    },
    rect10: {
        width: 14,
        height: 14,
        backgroundColor: "#E6E6E6",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun5: {
        color: "#3329FF",
        fontSize: 12,
        marginLeft: -4,
        marginTop: 5,
    },
    group14: {
        width: '14%',
        height: 14,
    },
    rect11: {
        width: 14,
        height: 14,
        backgroundColor: "#3329FF",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun6: {
        color: "#3329FF",
        fontSize: 12,
        marginLeft: -3,
        marginTop: 5,
    },
    group15: {
        width: '14%',
        height: 14,
    },
    rect12: {
        width: 14,
        height: 14,
        backgroundColor: "#E6E6E6",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun7: {
        color: "#3329FF",
        fontSize: 12,
        marginLeft: -3,
        marginTop: 5,
    },
    group16: {
        width: '14%',
        height: 14,
    },
    rect13: {
        width: 14,
        height: 14,
        backgroundColor: "#E6E6E6",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun8: {
        color: "#3329FF",
        fontSize: 12,
        marginLeft: 2.5,
        marginTop: 5,
    },
    group9: {
        width: '14%',
        height: 14,
    },
    rect7: {
        width: 14,
        height: 14,
        backgroundColor: "#E6E6E6",
        borderWidth: 2,
        borderColor: "#3329FF",
        borderRadius: 50,
        margin: 0,
        marginLeft: 2,
    },
    sun2: {
        color: "#3329FF",
        fontSize: 12,
        margin: 0,
        marginTop: 5,
    },
});